mozmorris/react-webcam

lib/react-webcam.js
window.URL.revokeObjectURL did not have correct case, and was throwing
=> invalid method name

README.md, src/react-webcam.js
In order to enable customize the video tag with some sort of CSS, it adds the props `className`
=> Add support to add custom class to video tag

src/react-webcam.js
`<Video>` will usually letterbox the original content if you force certain dimensions on it. Most times you want a screenshot that keeps the aspect ratio of the Webcam.
=> Preserve webcam aspect ratio while screenshoting

package.json, src/react-webcam.js
Added patch for requesting screenshot before video has fully loaded - which caused successive empty dataURIs - for example: “data:,”
=> Fix successive "empty" data URIs

README.md, src/react-webcam.js
Add video and audio constraint settings as props with existing fallback for MediaStreamTrack.getSources using the optional source id
=> refactor for audio and video constraints fixes #40

src/react-webcam.js
Is some cases, for example when modal view with Webcam components are closed before the user can 'Allow' the browser to use the webcam, the component get unmounted but userMediaRequested=false is never called.
Moving that line before the if statement can solve this problem.
=> userMediaRequested set to false every time the component unmount

README.md, src/react-webcam.js
Added props to disable imageSmoothingEnabled in canvas as it's adding a slight blur to screenshots taken (https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled)
=> Added props to disable imageSmoothingEnabled in canvas

README.md, src/react-webcam.tsx
If a mirrored option is needed, the video or container needs to be flip but the `getScreenshot` is returning a not mirrored image so the resulted image will always need an extra CSS to flip the image.
It also makes more difficult working with overlapping shapes on top of the image because you need to aware that it will be flip so -10px means +10px.
Add a mirrored prop that will display the video tag flip and modify the `getScreenshot` to return the image mirrored.
=> Mirrored camera option

src/react-webcam.tsx
The old polyfill got broken in commit ea3ed206 (navigator.getUserMedia
got replaced with navigator.mediaDevices.getUserMedia).
This new polyfill modifies the global navigator object unconditionally
when required and react-webcam is imported (the old one only changed
navigator.getUserMedia when media got requested by react-webcam).
If we decide to no longer polyfill for older browser, we can simply drop
one self containing method.
=> Cleanup 'getUserMedia' polyfill

README.md, src/react-webcam.tsx
This new property is useful when you request a larger video source via e.g. `videoConstraints={{ width: 1080}}`, but display it in a smaller preview place. When enabled, the screenshot has the full size of the source video stream, which also means that no resizing is necessary when drawing it to the canvas.
Default behavior does not change.
=> Add new property to force screenshot with same size as video source

src/__tests__/__snapshots__/react-webcam.tsx.snap, src/__tests__/react-webcam.tsx, src/react-webcam.tsx
As the component passes props down to the `<video>` tag, this allows the typescript definition to include the HTMLVideoElement props as part of the component.
I've also updated the test to show this working, as height/width are props on the `<video>` tag, not on the Webcam component
=> Update Typescript defintion to include HTMLVideoElement props

src/react-webcam.tsx
See issue https://github.com/mozmorris/react-webcam/issues/185
I have three webcams connected to my machine. When I change the stream source for one, it changes all video elements on the page. 
Before change: 
After this commit, each video element is independent and when I change the steam source for one, it does not update all video elements on the page anymore.
=> Remove loop in requestUserMedia for mounted devices

README.md
It might be nice to have a multiple camera example that uses `deviceId` in the Readme document. I used your codepen as the example.
=> Add multiple camera example to readme document

src/react-webcam.tsx
When you change constrains via props, a new #getUserMedia()
call got issued which leads in a new stream. The old stream
got not cleaned up and the tracks got not stopped. Without
stopping tracks, I was able to just get a black input on a
Huawei P30 device after switching between the different
environment cameras. Not revoking ObjectURLs leads in
memory leaks.
Use as testcase (device with multiple cameras required; alternative: add a "Dummy" button with a deviceId=dummy (which of course does not exist) and change `videoConstraints` to `{{ deviceId: {exact: deviceId} }}`): https://codepen.io/mozmorris/pen/KKwdOPO?editors=0010
=> Prevent resource leaks on constraint changes

src/react-webcam.tsx
Hello,
I want to create a component to check webcam and microphpne permissions for an application and I need to check microphone volume too. I'll be able to do it with the `stream` but this library make it private. So I just add it to the `onUserMedia` callback.
Here is an example : 
```js
import React, { useCallback, useState } from 'react'
import Webcam from 'react-webcam'
const videoConstraints = {
facingMode: 'user'
}
const listenMicrophoneLevel = (stream, cb) => {
const aduio = new AudioContext();
const analyser = aduio.createAnalyser();
const microphone = aduio.createMediaStreamSource(stream);
const processor = aduio.createScriptProcessor(2048, 1, 1);
analyser.smoothingTimeConstant = 0.8;
analyser.fftSize = 1024;
microphone.connect(analyser);
analyser.connect(processor); …
```
=> Add stream argument to onUserMedia callback

src/react-webcam.tsx
My fault, I realized that this only took custom dimension screenshots when the canvas is initialized. It never took custom dimension screenshots afterwards. I adjusted it here.
=> Add missing usage of width/height in getScreenshot

src/react-webcam.tsx
Issue: #272
Changed the parameter type. I was getting a `DOMException` back from the example code shown in #272, not a `string`.
=> fix: #272 onUserMediaError parameter type

src/react-webcam.tsx
Following this thread https://github.com/twilio/twilio-video-app-react/issues/355
Calling the `stream.removeTrack` before `.stop()` fixes the freezing issues in Android 11.
=> Fix Android 11 freezing issues

src/__tests__/__snapshots__/react-webcam.test.tsx.snap, src/__tests__/react-webcam.test.tsx, src/react-webcam.tsx
Closes #182.
Initial pass on this. Not sure what your philosophy is on writing tests;
I made mine check the actual node property instead of a snapshot to be
more explicit.
=> fix: properly set muted on video based on props.audio

src/react-webcam.tsx
If getUserMedia is multiple called before it resolves, use the latest stream and did not clean the unused streams.
ex: 
- getUserMedia is too slow and change constraints before getting the stream
- change constraints quickly
=> fix: Stream not cleaned when getUserMedia is multiple called

README.md, src/react-webcam.tsx
Using this approach we can get rid of useRef and useCallback when getting the screenshot
=> Using render props to simplify image capture

src/react-webcam.tsx
We only set the `unmounted` attribute value when unmounted, but not when mounted.
=> Stram could not be acquired

src/react-webcam.tsx
When the getScreenshot function gets called the first time, it creates a canvas object with given dimensions (if provided). From the next time onwards, it uses the same canvas to draw images. So, if someone passes different parameters the next time, it still uses the canvas built using parameters provided in the first time.
If we resize the canvas before drawing the image, it would resolve this issue.
=> adjust canvas dimensions according to parameters of getscreenshot function

README.md, src/__tests__/__snapshots__/react-webcam.test.tsx.snap, src/__tests__/react-webcam.test.tsx, src/react-webcam.tsx
This commit adds a new prop to the webcam component `disablePictureInPicture` which
as the name suggests, should disable this feature for any browser that supports it.
Defaults to false.
more context on the disablePictureInPicture property: https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/disablePictureInPicture
=> Support prop to disable Picture-in-Picture
